FROM debian:sid-20230208
LABEL maintainer="etienne.renault@lrde.epita.fr"

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && RUNLEVEL=1 DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
     automake \
     autoconf-archive \
     bison \
     clang-14 \
     clang-format \
     colordiff \
     cpio \
     curl \
     doxygen \
     flex \
     g++-11 \
     g++-11-multilib \
     gawk \
     gcc-11 \
     gcc-11-multilib \
     gettext \
     ghc \
     git \
     graphviz \
     imagemagick \
     latexmk \
     libboost-all-dev \
     libc6-i386 \
     libglib2.0-dev \
     libtool \
     lldb \
     m4 \
     make \
     python3 \
     python3-dev \
     python3-pip \
     python3-yaml \
     spim \
     ssh \
     swig \
     texinfo \
     texlive \
     texlive-font-utils \
     texlive-fonts-extra \
     texlive-luatex \
     wget \
     lcov \
     xz-utils

WORKDIR /opt/tiger

COPY install.sh requirements.txt /opt/tiger/

# HAVM, NOLIMIPS, BISON
RUN bash install.sh

# Dependencies for website
RUN pip3 install --break-system-packages -r /opt/tiger/requirements.txt pre-commit

# Default alternatives to fixed versions
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 110 &&\
    update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc \
        arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-11 110 &&\
    update-alternatives --install /usr/bin/gcc gcc  /usr/bin/gcc-11 110 &&\
    update-alternatives --install /usr/bin/g++ g++  /usr/bin/g++-11 110

# Default /bin/sh symlink to bash instead of dash
RUN echo "dash dash/sh boolean false" | debconf-set-selections \
    && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
